export const GET_NEWS_START = 'GET_NEWS_START';
export const GET_NEWS_SUCCESS = 'GET_NEWS_SUCCESS';
export const GET_NEWS_ERROR = 'GET_NEWS_ERROR';

export const GET_CATEGORIES_NEWS_START = 'GET_CATEGORIES_NEWS_START';
export const GET_CATEGORIES_NEWS_SUCCESS='GET_CATEGORIES_NEWS_SUCCESS';
export const GET_CATEGORIES_NEWS_ERROR = 'GET_CATEGORIES_NEWS_ERROR';